2023-05-04 16:11:44,316 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 41, in login
    if not next_page or url_unparse(next_page).netloc != '':
  File "D:\005Anaconda\lib\site-packages\werkzeug\urls.py", line 603, in url_unparse
    scheme, netloc, path, query, fragment = components
ValueError: too many values to unpack (expected 5)
2023-05-04 16:12:04,247 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 36, in login
    if user is None or not user.check_password(form.password.data):
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\models.py", line 29, in check_password
    return check_password_hash(self.password_hash, password)
  File "D:\005Anaconda\lib\site-packages\werkzeug\security.py", line 103, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2023-05-04 16:12:20,851 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 41, in login
    if not next_page or url_unparse(next_page).netloc != '':
  File "D:\005Anaconda\lib\site-packages\werkzeug\urls.py", line 603, in url_unparse
    scheme, netloc, path, query, fragment = components
ValueError: too many values to unpack (expected 5)
2023-05-04 16:15:36,886 INFO: Microblog startup [in D:\实验作业\2023-25 Web应用开发\project\code\11\app\__init__.py:49]
2023-05-04 16:15:53,619 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 41, in login
    if not next_page or url_unparse(next_page).netloc != '':
  File "D:\005Anaconda\lib\site-packages\werkzeug\urls.py", line 603, in url_unparse
    scheme, netloc, path, query, fragment = components
ValueError: too many values to unpack (expected 5)
2023-05-04 16:26:24,460 INFO: Microblog startup [in D:\实验作业\2023-25 Web应用开发\project\code\11\app\__init__.py:49]
2023-05-04 16:26:35,552 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 41, in login
    if not next_page or url_unparse(next_page).netloc != '':
  File "D:\005Anaconda\lib\site-packages\werkzeug\urls.py", line 603, in url_unparse
    scheme, netloc, path, query, fragment = components
ValueError: too many values to unpack (expected 5)
2023-05-04 16:26:47,317 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 36, in login
    if user is None or not user.check_password(form.password.data):
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\models.py", line 29, in check_password
    return check_password_hash(self.password_hash, password)
  File "D:\005Anaconda\lib\site-packages\werkzeug\security.py", line 103, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
2023-05-04 16:26:54,719 ERROR: Exception on /login [POST] [in D:\005Anaconda\lib\site-packages\flask\app.py:1744]
Traceback (most recent call last):
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\005Anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\routes.py", line 36, in login
    if user is None or not user.check_password(form.password.data):
  File "D:\实验作业\2023-25 Web应用开发\project\code\11\app\models.py", line 29, in check_password
    return check_password_hash(self.password_hash, password)
  File "D:\005Anaconda\lib\site-packages\werkzeug\security.py", line 103, in check_password_hash
    if pwhash.count("$") < 2:
AttributeError: 'NoneType' object has no attribute 'count'
